@startuml starter_template_c4
!include c4/C4_Chinese_Version.puml

title PlantUML for C4
right header [Your name/Company name]
footer © 2019 [Your name/Company name] All Rights Reversed

System(system, "XXX智能化系统", "提供各类信息管理服务")
Person(member, "普通用户")
Person(admin, "管理员")

Rel(member, system, "浏览器")
Rel(admin, system, "浏览器")
@enduml