@startuml starter_template_c4
' 在中国用gitee源，否则用github源
' Use gitee origin in China, otherwise use github origin
!$gitee_origin = "https://gitee.com/jarrodquan/plantuml-style/raw/master/"
!$github_origin = "https://raw.githubusercontent.com/jarrodquan/plantuml-style/master/"

' 必须定义的变量：origin_url，head_url
' Variable that must be defined: origin_url, head_url
!$origin_url = $gitee_origin
!$head_url = $origin_url + "head.puml"

' 必须包含的引用：head_url
' Reference that must be included: head_url
' 英文版：替换“!includeurl $c4_chinese_version_url”为“!includeurl $c4_component_url”
' English version: Replace "!includeurl $c4_chinese_version_url" to "!includeurl $c4_component_url"
!include $head_url
!includeurl $c4_chinese_version_url

title PlantUML for C4
right header [Your name/Company name]
footer © 2019 [Your name/Company name] All Rights Reversed

System(system, "XXX智能化系统", "提供各类信息管理服务")
Person(member, "普通用户")
Person(admin, "管理员")

Rel(member, system, "浏览器")
Rel(admin, system, "浏览器")
@enduml