@startuml starter_template
!include style/core.puml

title Sequence Diagram
right header [Your name/Company name]
footer © 2019 [Your name/Company name] All Rights Reversed

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml